#!/usr/bin/env python3
"""Refresh the machine-generated repository-size block inside AGENTS.md.

AGENTS.md is the lightweight AI entry point for this repository. Most of the
file is narrative that humans / agents edit by hand. This script rewrites one
fenced region:

  * STABLE  (between AGENTS-AUTO markers) — repository-size counts. These change
    only when files are added or removed, and they are stable across a commit
    boundary, so ``--check`` enforces them (e.g. in scripts/publish_public.sh).
    Volatile Git state is intentionally not written here; use ``git status`` for
    the current branch, HEAD, and worktree.

Usage:
    python3 scripts/update_agents_guide.py            # rewrite the stable region
    python3 scripts/update_agents_guide.py --check     # exit 1 if STABLE is stale
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from collection_registry import collection_roots

AUTO_BEGIN = "<!-- AGENTS-AUTO:BEGIN -->"
AUTO_END = "<!-- AGENTS-AUTO:END -->"

CHAPTER_RE = re.compile(r"-ch\d{3}\.md$")


def git(repo: Path, *args: str) -> str:
    """Run a git command at ``repo`` and return stripped stdout (or "")."""
    try:
        out = subprocess.run(
            ["git", *args],
            cwd=repo,
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""
    return out.stdout.strip()


def repo_root() -> Path:
    top = git(Path.cwd(), "rev-parse", "--show-toplevel")
    if not top:
        sys.exit("error: not inside a git repository")
    return Path(top)


def build_stable(repo: Path) -> str:
    """Repo-size facts: stable across a commit boundary, enforced by --check."""
    tracked = [f for f in git(repo, "ls-files").splitlines() if f]
    md = [f for f in tracked if f.endswith(".md")]
    chapters = [f for f in md if CHAPTER_RE.search(f)]
    corpus_md = [f for f in md if f.startswith(collection_roots(repo))]
    work_manifests = [f for f in tracked if f.endswith("work_manifest.json")]
    branch = git(repo, "rev-parse", "--abbrev-ref", "HEAD") or "(detached)"
    return "\n".join(
        [
            AUTO_BEGIN,
            "<!-- Generated by scripts/update_agents_guide.py; --check enforces this block. -->",
            "",
            "**Repository Size** (why agents should not read the whole repository)",
            "",
            "| Tracked files | Markdown | Corpus md | Chapter files | Split works | Branch |",
            "|---:|---:|---:|---:|---:|:--|",
            f"| {len(tracked)} | {len(md)} | {len(corpus_md)} | "
            f"{len(chapters)} | {len(work_manifests)} | `{branch}` |",
            "",
            AUTO_END,
        ]
    )


def splice(text: str, begin: str, end: str, block: str, *, required: bool) -> str:
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        if required:
            sys.exit(
                f"error: markers not found in AGENTS.md\n"
                f"       expected a region between {begin!r} and {end!r}"
            )
        return text
    return pattern.sub(lambda _: block, text, count=1)


def region(text: str, begin: str, end: str) -> str:
    m = re.search(re.escape(begin) + r".*?" + re.escape(end), text, re.DOTALL)
    return m.group(0) if m else ""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the STABLE block is stale instead of rewriting",
    )
    args = parser.parse_args()

    repo = repo_root()
    target = repo / "AGENTS.md"
    if not target.exists():
        sys.exit(f"error: {target} does not exist")

    current = target.read_text(encoding="utf-8")
    stable = build_stable(repo)

    if args.check:
        if region(current, AUTO_BEGIN, AUTO_END) != stable:
            print(
                "AGENTS.md size block is stale. "
                "Run: python3 scripts/update_agents_guide.py",
                file=sys.stderr,
            )
            return 1
        print("AGENTS.md size block is up to date.")
        return 0

    updated = splice(current, AUTO_BEGIN, AUTO_END, stable, required=True)
    if current != updated:
        target.write_text(updated, encoding="utf-8")
        print("AGENTS.md repository-size block refreshed.")
    else:
        print("AGENTS.md repository-size block already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
